#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <developer@mplx.eu>
#
# Stamp a version into src/topics/version.j, the VERSION constant the deck
# exports.
#
# This does NOT touch deck.toml. package.version is authored and committed,
# because jvc resolves against the manifest on the default branch: it reads
# package.urls.deck, which points at raw.githubusercontent.com/.../main/
# deck.toml. A version that only ever existed inside a CI workspace would
# leave jvc resolving whatever was last committed. Bump the manifest, then
# tag to match; release.yml refuses a tag that disagrees.
#
# src/topics/version.j is generated, so `d64.VERSION` says which build this
# is: the tag on a release, <tag>-dev+<commits>.<sha> on a branch.
#
# Usage: tools/inject-version.sh [version]   (default: tools/version.sh)
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=tools/deck-lib.sh
source tools/deck-lib.sh

version="${1:-$(tools/version.sh)}"

# Semver, optionally with a -dev prerelease and +build metadata.
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
    deck_die "\"${version}\" is not a semver version"
fi

license="$(deck_field package.license)"
floor="$(deck_field engines.jennifer)"

cat > src/topics/version.j <<EOF
# SPDX-License-Identifier: ${license}
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <developer@mplx.eu>
# pragma-jennifer-version: ${floor}
# ci-no-overlay

# d64 - generated by tools/inject-version.sh. Do not edit.
# Spliced into d64.j via include - not a standalone module.

/**
 * The version of this deck.
 *
 * Injected from the git tag the build came from: \`0.2.0\` on a release,
 * \`0.2.0-dev+14.9ebf3dd\` anywhere else. See tools/version.sh.
 */
export def const VERSION as string init "${version}";
EOF

echo "injected ${version} into src/topics/version.j"
